/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : extWdog.c
**     Project     : lowersystem
**     Processor   : S32K144_64
**     Component   : ewm
**     Version     : Component SDK_S32K1xx_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-03-06, 11:16, # CodeGen: 374
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file extWdog.c
** @version 01.00
*/         
/*!
**  @addtogroup extWdog_module extWdog module documentation
**  @{
*/         

/* MODULE extWdog.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files by the user.
 */

#include "extWdog.h"


/*! @brief extWdog configuration structures */

    
/*! 
 * Configuration extWdog_Config0
    -   508 ms counter period
    -   508 ms refresh window 
 */
ewm_init_config_t extWdog_Config0 = {
    /* Module interrupt enabled */
    .interruptEnable    =   true,   
    /* Prescaler */
    .prescaler          =   255U,  
    /* Compare Low Value        */    
    .compareLow         =   0U,   
    /* Compare High Value       */    
    .compareHigh        =   254U, 
    /* Input pin logic          */
    .assertLogic        =   EWM_IN_ASSERT_DISABLED
};
/* END extWdog. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/



