/**
 * @file   gen_can_matrix.h
 * @author Auto generated
 * @note   Created on 2020/5/28 
 */

#ifndef __GEN_CAN_MATRIX_H__
#define __GEN_CAN_MATRIX_H__

/******************************************************************************
 * Definitions
 ******************************************************************************/
#define                                                         YEMA            /**< Vehicle Factory */
#define                                                         MOTOROLA        /**< Byte Order */

/**
 * @name CAN0 messages.
 * @{
 */
/* Message DVD_3E8h */
#define MSG_ID_DVD_3E8h                                         0x3E8
#define SIGNAL_DVD_Second_START_BIT                             0
#define SIGNAL_DVD_Second_BIT_LEN                               6
#define SIGNAL_DVD_Minute_START_BIT                             8
#define SIGNAL_DVD_Minute_BIT_LEN                               6
#define SIGNAL_DVD_Hour_START_BIT                               16
#define SIGNAL_DVD_Hour_BIT_LEN                                 5
#define SIGNAL_DVD_Day_START_BIT                                24
#define SIGNAL_DVD_Day_BIT_LEN                                  5
#define SIGNAL_DVD_Month_START_BIT                              32
#define SIGNAL_DVD_Month_BIT_LEN                                4
#define SIGNAL_DVD_Year_START_BIT                               40
#define SIGNAL_DVD_Year_BIT_LEN                                 6
/* Message DVD_3E9h */
#define MSG_ID_DVD_3E9h                                         0x3E9
#define SIGNAL_TboxSwitch_START_BIT                             4
#define SIGNAL_TboxSwitch_BIT_LEN                               2
#define SIGNAL_ChargeModeSelection_START_BIT                    21
#define SIGNAL_ChargeModeSelection_BIT_LEN                      3
#define SIGNAL_ChargeStart_START_BIT                            19
#define SIGNAL_ChargeStart_BIT_LEN                              2
#define SIGNAL_DVDPrivateInfoLock_START_BIT                     31
#define SIGNAL_DVDPrivateInfoLock_BIT_LEN                       1
#define SIGNAL_ElectronicLock_Unlock_START_BIT                  35
#define SIGNAL_ElectronicLock_Unlock_BIT_LEN                    2
#define SIGNAL_DischargeStart_START_BIT                         33
#define SIGNAL_DischargeStart_BIT_LEN                           2
/* Message GW_EMS_3F5h */
#define MSG_ID_GW_EMS_3F5h                                      0x3F5
#define SIGNAL_ActualGearFromEMS_START_BIT                      2
#define SIGNAL_ActualGearFromEMS_BIT_LEN                        4
#define SIGNAL_ActualGearFromEMSFailFlag_START_BIT              1
#define SIGNAL_ActualGearFromEMSFailFlag_BIT_LEN                1
/* Message Tbox_424h */
#define MSG_ID_Tbox_424h                                        0x424
#define SIGNAL_TBoxNMDestinationAddress_START_BIT               0
#define SIGNAL_TBoxNMDestinationAddress_BIT_LEN                 8
#define SIGNAL_TBoxNMAlive_START_BIT                            15
#define SIGNAL_TBoxNMAlive_BIT_LEN                              1
#define SIGNAL_TBoxNMRing_START_BIT                             14
#define SIGNAL_TBoxNMRing_BIT_LEN                               1
#define SIGNAL_TBoxNMLimphome_START_BIT                         13
#define SIGNAL_TBoxNMLimphome_BIT_LEN                           1
#define SIGNAL_TBoxNMSleepIndication_START_BIT                  11
#define SIGNAL_TBoxNMSleepIndication_BIT_LEN                    1
#define SIGNAL_TBoxNMSleepAcknowledge_START_BIT                 10
#define SIGNAL_TBoxNMSleepAcknowledge_BIT_LEN                   1
/* Message Tbox_089h */
#define MSG_ID_Tbox_089h                                        0x89
#define SIGNAL_TBOX_MessageType_START_BIT                       4
#define SIGNAL_TBOX_MessageType_BIT_LEN                         4
#define SIGNAL_TBox_PEPSCode1_START_BIT                         8
#define SIGNAL_TBox_PEPSCode1_BIT_LEN                           8
#define SIGNAL_TBox_PEPSCode2_START_BIT                         16
#define SIGNAL_TBox_PEPSCode2_BIT_LEN                           8
#define SIGNAL_TBox_PEPSCode3_START_BIT                         24
#define SIGNAL_TBox_PEPSCode3_BIT_LEN                           8
#define SIGNAL_TBox_PEPSCode4_START_BIT                         32
#define SIGNAL_TBox_PEPSCode4_BIT_LEN                           8
#define SIGNAL_TBox_PEPSCode5_START_BIT                         40
#define SIGNAL_TBox_PEPSCode5_BIT_LEN                           8
#define SIGNAL_TBox_PEPSCode6_START_BIT                         48
#define SIGNAL_TBox_PEPSCode6_BIT_LEN                           8
#define SIGNAL_TBox_089_CheckSum_START_BIT                      60
#define SIGNAL_TBox_089_CheckSum_BIT_LEN                        4
#define SIGNAL_TBox_089_RollingCounter_START_BIT                56
#define SIGNAL_TBox_089_RollingCounter_BIT_LEN                  4
/* Message PEPS_090h */
#define MSG_ID_PEPS_090h                                        0x90
#define SIGNAL_PEPS_TBOX_MessageType_START_BIT                  4
#define SIGNAL_PEPS_TBOX_MessageType_BIT_LEN                    4
#define SIGNAL_Negative_response_START_BIT                      0
#define SIGNAL_Negative_response_BIT_LEN                        4
#define SIGNAL_PEPS_TBoxCode1_START_BIT                         8
#define SIGNAL_PEPS_TBoxCode1_BIT_LEN                           8
#define SIGNAL_PEPS_TBoxCode2_START_BIT                         16
#define SIGNAL_PEPS_TBoxCode2_BIT_LEN                           8
#define SIGNAL_PEPS_TBoxCode3_START_BIT                         24
#define SIGNAL_PEPS_TBoxCode3_BIT_LEN                           8
#define SIGNAL_PEPS_TBoxCode4_START_BIT                         32
#define SIGNAL_PEPS_TBoxCode4_BIT_LEN                           8
#define SIGNAL_PEPS_TBoxCode5_START_BIT                         40
#define SIGNAL_PEPS_TBoxCode5_BIT_LEN                           8
#define SIGNAL_PEPS_TBoxCode6_START_BIT                         48
#define SIGNAL_PEPS_TBoxCode6_BIT_LEN                           8
#define SIGNAL_PEPS_090_CheckSum_START_BIT                      60
#define SIGNAL_PEPS_090_CheckSum_BIT_LEN                        4
#define SIGNAL_PEPS_090_RollingCounter_START_BIT                56
#define SIGNAL_PEPS_090_RollingCounter_BIT_LEN                  4
/* Message GW_EMS_117h_CVT */
#define MSG_ID_GW_EMS_117h_CVT                                  0x115
#define SIGNAL_EngState_START_BIT                               56
#define SIGNAL_EngState_BIT_LEN                                 3
/* Message GW_EMS_117h_AT */
#define MSG_ID_GW_EMS_117h_AT                                   0x116
#define SIGNAL_EngState1_START_BIT                              56
#define SIGNAL_EngState1_BIT_LEN                                3
/* Message GW_EMS_117h_DCT */
#define MSG_ID_GW_EMS_117h_DCT                                  0x117
#define SIGNAL_EngState_DCT_START_BIT                           56
#define SIGNAL_EngState_DCT_BIT_LEN                             3
/* Message GW_VCU_119h */
#define MSG_ID_GW_VCU_119h                                      0x119
#define SIGNAL_VCU_VehicleSpeedValid_START_BIT                  53
#define SIGNAL_VCU_VehicleSpeedValid_BIT_LEN                    1
#define SIGNAL_VCU_VehicleSpeed_START_BIT                       40
#define SIGNAL_VCU_VehicleSpeed_BIT_LEN                         13
/* Message GW_EMS_123h */
#define MSG_ID_GW_EMS_123h                                      0x123
#define SIGNAL_EngineSpeedRPM_START_BIT                         0
#define SIGNAL_EngineSpeedRPM_BIT_LEN                           16
#define SIGNAL_AccelerationPedalPosition_START_BIT              24
#define SIGNAL_AccelerationPedalPosition_BIT_LEN                8
#define SIGNAL_BrakePedalStatus_START_BIT                       37
#define SIGNAL_BrakePedalStatus_BIT_LEN                         2
#define SIGNAL_ACCompressorStatus_START_BIT                     40
#define SIGNAL_ACCompressorStatus_BIT_LEN                       1
/* Message GW_TCU_141h */
#define MSG_ID_GW_TCU_141h                                      0x141
#define SIGNAL_GearboxOilTemp_START_BIT                         0
#define SIGNAL_GearboxOilTemp_BIT_LEN                           8
#define SIGNAL_ActualGear_START_BIT                             8
#define SIGNAL_ActualGear_BIT_LEN                               4
#define SIGNAL_DriveMode_START_BIT                              32
#define SIGNAL_DriveMode_BIT_LEN                                3
/* Message GW_ESP_218h */
#define MSG_ID_GW_ESP_218h                                      0x218
#define SIGNAL_VehicleSpeedValid_START_BIT                      3
#define SIGNAL_VehicleSpeedValid_BIT_LEN                        1
#define SIGNAL_ABSFailStatus_START_BIT                          1
#define SIGNAL_ABSFailStatus_BIT_LEN                            1
#define SIGNAL_VehicleSpeed_START_BIT                           8
#define SIGNAL_VehicleSpeed_BIT_LEN                             13
/* Message GW_ESP_228h */
#define MSG_ID_GW_ESP_228h                                      0x228
#define SIGNAL_ESPActiveLampInfo_START_BIT                      2
#define SIGNAL_ESPActiveLampInfo_BIT_LEN                        1
#define SIGNAL_Pala_ESPONOffLamp_START_BIT                      1
#define SIGNAL_Pala_ESPONOffLamp_BIT_LEN                        1
/* Message GW_EPS_230h */
#define MSG_ID_GW_EPS_230h                                      0x230
#define SIGNAL_SteeringWheelAngle_START_BIT                     0
#define SIGNAL_SteeringWheelAngle_BIT_LEN                       16
#define SIGNAL_SteeringSpeed_START_BIT                          16
#define SIGNAL_SteeringSpeed_BIT_LEN                            8
/* Message GW_ACC_233h */
#define MSG_ID_GW_ACC_233h                                      0x233
#define SIGNAL_ACC_TextInfoForDriver_START_BIT                  28
#define SIGNAL_ACC_TextInfoForDriver_BIT_LEN                    4
/* Message GW_EMS_301h */
#define MSG_ID_GW_EMS_301h                                      0x301
#define SIGNAL_EngineCoolantTemperature_START_BIT               0
#define SIGNAL_EngineCoolantTemperature_BIT_LEN                 8
#define SIGNAL_EngineSVSSignal_START_BIT                        28
#define SIGNAL_EngineSVSSignal_BIT_LEN                          1
/* Message GW_SRS_318h */
#define MSG_ID_GW_SRS_318h                                      0x318
#define SIGNAL_PsSeatBeltRSt_START_BIT                          18
#define SIGNAL_PsSeatBeltRSt_BIT_LEN                            2
#define SIGNAL_DrvSeatBeltRSt_START_BIT                         16
#define SIGNAL_DrvSeatBeltRSt_BIT_LEN                           2
#define SIGNAL_CrashOutputSts_START_BIT                         24
#define SIGNAL_CrashOutputSts_BIT_LEN                           8
/* Message IC_328h */
#define MSG_ID_IC_328h                                          0x328
#define SIGNAL_HandBrakeSts_START_BIT                           2
#define SIGNAL_HandBrakeSts_BIT_LEN                             1
#define SIGNAL_IC_ODOmeter_START_BIT                            8
#define SIGNAL_IC_ODOmeter_BIT_LEN                              24
#define SIGNAL_IC_EnduranceMileage_START_BIT                    32
#define SIGNAL_IC_EnduranceMileage_BIT_LEN                      12
#define SIGNAL_IC_vDisplay_Reserved_START_BIT                   44
#define SIGNAL_IC_vDisplay_Reserved_BIT_LEN                     12
#define SIGNAL_IC_vDisplay_AVG_START_BIT                        56
#define SIGNAL_IC_vDisplay_AVG_BIT_LEN                          8
/* Message GW_TCU_333h */
#define MSG_ID_GW_TCU_333h                                      0x333
#define SIGNAL_GearboxOilWrnLmpReq_START_BIT                    4
#define SIGNAL_GearboxOilWrnLmpReq_BIT_LEN                      1
#define SIGNAL_StatusGearboxWarningLight_START_BIT              1
#define SIGNAL_StatusGearboxWarningLight_BIT_LEN                1
#define SIGNAL_GearBoxFaultStatus_START_BIT                     9
#define SIGNAL_GearBoxFaultStatus_BIT_LEN                       1
/* Message Tbox_360h */
#define MSG_ID_Tbox_360h                                        0x360
#define SIGNAL_RemoteEngineControlEDReqValid_START_BIT          7
#define SIGNAL_RemoteEngineControlEDReqValid_BIT_LEN            1
#define SIGNAL_RemoteEngineControlEDReq_START_BIT               5
#define SIGNAL_RemoteEngineControlEDReq_BIT_LEN                 2
#define SIGNAL_RemotePowerControlReqValid_START_BIT             4
#define SIGNAL_RemotePowerControlReqValid_BIT_LEN               1
#define SIGNAL_RemotePowerControlReq_START_BIT                  2
#define SIGNAL_RemotePowerControlReq_BIT_LEN                    2
#define SIGNAL_RemoteVehicleTrackingReq_START_BIT               1
#define SIGNAL_RemoteVehicleTrackingReq_BIT_LEN                 1
#define SIGNAL_RemoteVehicleTrackingReqValid_START_BIT          0
#define SIGNAL_RemoteVehicleTrackingReqValid_BIT_LEN            1
#define SIGNAL_RemoteEngineControlSSReqValid_START_BIT          15
#define SIGNAL_RemoteEngineControlSSReqValid_BIT_LEN            1
#define SIGNAL_RemoteEngineControlSSReq_START_BIT               13
#define SIGNAL_RemoteEngineControlSSReq_BIT_LEN                 2
#define SIGNAL_RemoteACControlReqModeValid_START_BIT            12
#define SIGNAL_RemoteACControlReqModeValid_BIT_LEN              1
#define SIGNAL_RemoteACControlReqMode_START_BIT                 8
#define SIGNAL_RemoteACControlReqMode_BIT_LEN                   4
#define SIGNAL_RemoteACControlTemperature_START_BIT             16
#define SIGNAL_RemoteACControlTemperature_BIT_LEN               8
#define SIGNAL_RemoteBCMControlLockReqValid_START_BIT           31
#define SIGNAL_RemoteBCMControlLockReqValid_BIT_LEN             1
#define SIGNAL_RemoteBCMControlLockReq_START_BIT                28
#define SIGNAL_RemoteBCMControlLockReq_BIT_LEN                  3
#define SIGNAL_RemoteACSeatHotReqValid_START_BIT                27
#define SIGNAL_RemoteACSeatHotReqValid_BIT_LEN                  1
#define SIGNAL_RemoteACSeatHotReq_START_BIT                     24
#define SIGNAL_RemoteACSeatHotReq_BIT_LEN                       3
#define SIGNAL_RemoteBCMControlWinReqValidValid_START_BIT       39
#define SIGNAL_RemoteBCMControlWinReqValidValid_BIT_LEN         1
#define SIGNAL_RemoteBCMControWinlReq_START_BIT                 36
#define SIGNAL_RemoteBCMControWinlReq_BIT_LEN                   3
#define SIGNAL_RemoteBCMSunroofReqValid_START_BIT               35
#define SIGNAL_RemoteBCMSunroofReqValid_BIT_LEN                 1
#define SIGNAL_RemoteBCMSunroofReq_START_BIT                    32
#define SIGNAL_RemoteBCMSunroofReq_BIT_LEN                      3
#define SIGNAL_RemoteRmtChargeCmdValid_START_BIT                47
#define SIGNAL_RemoteRmtChargeCmdValid_BIT_LEN                  1
#define SIGNAL_RemoteRmtChargeCmd_START_BIT                     45
#define SIGNAL_RemoteRmtChargeCmd_BIT_LEN                       2
#define SIGNAL_RemoteVehicleStsReqValid_START_BIT               44
#define SIGNAL_RemoteVehicleStsReqValid_BIT_LEN                 1
#define SIGNAL_RemoteVehicleStsReq_START_BIT                    42
#define SIGNAL_RemoteVehicleStsReq_BIT_LEN                      2
#define SIGNAL_Reserved1_START_BIT                              41
#define SIGNAL_Reserved1_BIT_LEN                                1
#define SIGNAL_Reserved2_START_BIT                              40
#define SIGNAL_Reserved2_BIT_LEN                                1
#define SIGNAL_RollingCounter_TBox1_START_BIT                   52
#define SIGNAL_RollingCounter_TBox1_BIT_LEN                     4
#define SIGNAL_RemoteDVDPrivateInfoLockReqValid_START_BIT       51
#define SIGNAL_RemoteDVDPrivateInfoLockReqValid_BIT_LEN         1
#define SIGNAL_RemoteDVDPrivateInfoLockReq_START_BIT            48
#define SIGNAL_RemoteDVDPrivateInfoLockReq_BIT_LEN              3
#define SIGNAL_CheckSum_TBox1_START_BIT                         56
#define SIGNAL_CheckSum_TBox1_BIT_LEN                           8
/* Message TPMS_390h */
#define MSG_ID_TPMS_390h                                        0x390
#define SIGNAL_TPMSTransducerSn_START_BIT                       0
#define SIGNAL_TPMSTransducerSn_BIT_LEN                         4
#define SIGNAL_TirePressure_START_BIT                           8
#define SIGNAL_TirePressure_BIT_LEN                             8
#define SIGNAL_TireTemperature_START_BIT                        16
#define SIGNAL_TireTemperature_BIT_LEN                          8
#define SIGNAL_MsgInValidStu_START_BIT                          31
#define SIGNAL_MsgInValidStu_BIT_LEN                            1
/* Message BCM_3A0h */
#define MSG_ID_BCM_3A0h                                         0x3A0
#define SIGNAL_LHTurnSignalSts_START_BIT                        7
#define SIGNAL_LHTurnSignalSts_BIT_LEN                          1
#define SIGNAL_RearfoglightfailSts_START_BIT                    6
#define SIGNAL_RearfoglightfailSts_BIT_LEN                      1
#define SIGNAL_RearFogLightSts_START_BIT                        5
#define SIGNAL_RearFogLightSts_BIT_LEN                          1
#define SIGNAL_FrontFogLightSts_START_BIT                       4
#define SIGNAL_FrontFogLightSts_BIT_LEN                         1
#define SIGNAL_LowBeamSts_START_BIT                             3
#define SIGNAL_LowBeamSts_BIT_LEN                               1
#define SIGNAL_HighBeamSts_START_BIT                            2
#define SIGNAL_HighBeamSts_BIT_LEN                              1
#define SIGNAL_ParkLightFailSts_START_BIT                       1
#define SIGNAL_ParkLightFailSts_BIT_LEN                         1
#define SIGNAL_ParkingLightSts_START_BIT                        0
#define SIGNAL_ParkingLightSts_BIT_LEN                          1
#define SIGNAL_LHFDoorSts_START_BIT                             15
#define SIGNAL_LHFDoorSts_BIT_LEN                               1
#define SIGNAL_LHRDoorSts_START_BIT                             14
#define SIGNAL_LHRDoorSts_BIT_LEN                               1
#define SIGNAL_RHRDoorSts_START_BIT                             13
#define SIGNAL_RHRDoorSts_BIT_LEN                               1
#define SIGNAL_BackDoorSts_START_BIT                            12
#define SIGNAL_BackDoorSts_BIT_LEN                              1
#define SIGNAL_RHTurnSignalSts_START_BIT                        8
#define SIGNAL_RHTurnSignalSts_BIT_LEN                          1
#define SIGNAL_KeySts_START_BIT                                 17
#define SIGNAL_KeySts_BIT_LEN                                   4
#define SIGNAL_RHFDoorSts_START_BIT                             16
#define SIGNAL_RHFDoorSts_BIT_LEN                               1
#define SIGNAL_RearDfstSts_START_BIT                            31
#define SIGNAL_RearDfstSts_BIT_LEN                              1
#define SIGNAL_BatteryVoltageLevel_START_BIT                    24
#define SIGNAL_BatteryVoltageLevel_BIT_LEN                      7
#define SIGNAL_WiperSts_START_BIT                               35
#define SIGNAL_WiperSts_BIT_LEN                                 2
#define SIGNAL_FLDoorlock_START_BIT                             47
#define SIGNAL_FLDoorlock_BIT_LEN                               1
#define SIGNAL_FRDoorlock_START_BIT                             46
#define SIGNAL_FRDoorlock_BIT_LEN                               1
#define SIGNAL_RLDoorlock_START_BIT                             45
#define SIGNAL_RLDoorlock_BIT_LEN                               1
#define SIGNAL_RRDoorlock_START_BIT                             44
#define SIGNAL_RRDoorlock_BIT_LEN                               1
#define SIGNAL_RearMirrorFoldStates_START_BIT                   43
#define SIGNAL_RearMirrorFoldStates_BIT_LEN                     1
#define SIGNAL_BackDoorlock_START_BIT                           42
#define SIGNAL_BackDoorlock_BIT_LEN                             1
#define SIGNAL_BodyGuardAgainstTheft_START_BIT                  40
#define SIGNAL_BodyGuardAgainstTheft_BIT_LEN                    2
/* Message AC_3B0h */
#define MSG_ID_AC_3B0h                                          0x3B0
#define SIGNAL_ExternalTemperature_START_BIT                    0
#define SIGNAL_ExternalTemperature_BIT_LEN                      8
#define SIGNAL_BLW_Status_START_BIT                             11
#define SIGNAL_BLW_Status_BIT_LEN                               3
#define SIGNAL_ExternalTemperatureFailSts_START_BIT             8
#define SIGNAL_ExternalTemperatureFailSts_BIT_LEN               1
#define SIGNAL_Temparature_inside1_START_BIT                    16
#define SIGNAL_Temparature_inside1_BIT_LEN                      8
#define SIGNAL_Temparature_inside2_START_BIT                    24
#define SIGNAL_Temparature_inside2_BIT_LEN                      8
#define SIGNAL_AC_KeyAC_START_BIT                               38
#define SIGNAL_AC_KeyAC_BIT_LEN                                 1
#define SIGNAL_AC_KeyRearDeFrost_START_BIT                      37
#define SIGNAL_AC_KeyRearDeFrost_BIT_LEN                        1
#define SIGNAL_AC_KeyFrontDeFrost_START_BIT                     36
#define SIGNAL_AC_KeyFrontDeFrost_BIT_LEN                       1
#define SIGNAL_AC_Keycycle_START_BIT                            35
#define SIGNAL_AC_Keycycle_BIT_LEN                              1
#define SIGNAL_AC_Keymode_START_BIT                             32
#define SIGNAL_AC_Keymode_BIT_LEN                               3
#define SIGNAL_AC_AirVolumeControl1_START_BIT                   44
#define SIGNAL_AC_AirVolumeControl1_BIT_LEN                     4
#define SIGNAL_AC_AirVolumeControl2_START_BIT                   40
#define SIGNAL_AC_AirVolumeControl2_BIT_LEN                     4
/* Message BCM_3C5h */
#define MSG_ID_BCM_3C5h                                         0x3C5
#define SIGNAL_SCU_GlassStatus_START_BIT                        5
#define SIGNAL_SCU_GlassStatus_BIT_LEN                          3
#define SIGNAL_SCU_CurtainStatus_START_BIT                      2
#define SIGNAL_SCU_CurtainStatus_BIT_LEN                        3
#define SIGNAL_SCU_GlassPos_START_BIT                           14
#define SIGNAL_SCU_GlassPos_BIT_LEN                             2
#define SIGNAL_FLWindowSts_START_BIT                            11
#define SIGNAL_FLWindowSts_BIT_LEN                              3
#define SIGNAL_FRWindowSts_START_BIT                            8
#define SIGNAL_FRWindowSts_BIT_LEN                              3
#define SIGNAL_FL_OpenedVal_START_BIT                           17
#define SIGNAL_FL_OpenedVal_BIT_LEN                             7
#define SIGNAL_FR_OpenedVal_START_BIT                           25
#define SIGNAL_FR_OpenedVal_BIT_LEN                             7
#define SIGNAL_RLWindowSts_START_BIT                            37
#define SIGNAL_RLWindowSts_BIT_LEN                              3
#define SIGNAL_RRWindowSts_START_BIT                            34
#define SIGNAL_RRWindowSts_BIT_LEN                              3
#define SIGNAL_RL_OpenedVal_START_BIT                           41
#define SIGNAL_RL_OpenedVal_BIT_LEN                             7
#define SIGNAL_RR_OpenedVal_START_BIT                           49
#define SIGNAL_RR_OpenedVal_BIT_LEN                             7
/* Message BCM_3C6h */
#define MSG_ID_BCM_3C6h                                         0x3C6
#define SIGNAL_Node_name_START_BIT                              0
#define SIGNAL_Node_name_BIT_LEN                                8
#define SIGNAL_Release_Time_START_BIT                           8
#define SIGNAL_Release_Time_BIT_LEN                             16
#define SIGNAL_Version_START_BIT                                24
#define SIGNAL_Version_BIT_LEN                                  16
#define SIGNAL_Project_No_START_BIT                             40
#define SIGNAL_Project_No_BIT_LEN                               24

#define CAN0_MSG_ID_NUM                                         26

#define CAN0_MSG_ID_LIST 0x3E8, 0x3E9, 0x3F5, 0x424, 0x89, 0x90, 0x115, 0x116, 0x117, 0x119, 0x123, 0x141, 0x218, 0x228, 0x230, 0x233, 0x301, 0x318, 0x328, 0x333, 0x360, 0x390, 0x3A0, 0x3B0, 0x3C5, 0x3C6
/** @} */ /* CAN0 messages. */

/**
 * @name CAN1 messages.
 * @{
 */
/* Message VCU_118h */
#define MSG_ID_VCU_118h                                         0x118
#define SIGNAL_VCU_ShftLvlPos_START_BIT                         5
#define SIGNAL_VCU_ShftLvlPos_BIT_LEN                           3
#define SIGNAL_VCU_BrkPdlStsV_START_BIT                         4
#define SIGNAL_VCU_BrkPdlStsV_BIT_LEN                           1
#define SIGNAL_VCU_BrkPdlSts_START_BIT                          3
#define SIGNAL_VCU_BrkPdlSts_BIT_LEN                            1
#define SIGNAL_VCU_BrkPdlPosV_START_BIT                         2
#define SIGNAL_VCU_BrkPdlPosV_BIT_LEN                           1
#define SIGNAL_VCU_AccelPdlPosV_START_BIT                       1
#define SIGNAL_VCU_AccelPdlPosV_BIT_LEN                         1
#define SIGNAL_VCU_BrkPdlPos_START_BIT                          8
#define SIGNAL_VCU_BrkPdlPos_BIT_LEN                            8
#define SIGNAL_VCU_AccelPdlPos_START_BIT                        16
#define SIGNAL_VCU_AccelPdlPos_BIT_LEN                          8
/* Message VCU_126h */
#define MSG_ID_VCU_126h                                         0x126
#define SIGNAL_VCU_PtRdy_START_BIT                              2
#define SIGNAL_VCU_PtRdy_BIT_LEN                                1
#define SIGNAL_VCU_VehSysFlt_START_BIT                          15
#define SIGNAL_VCU_VehSysFlt_BIT_LEN                            1
#define SIGNAL_VCU_SysFaulev_START_BIT                          13
#define SIGNAL_VCU_SysFaulev_BIT_LEN                            2
#define SIGNAL_VCU_HVILClsdFlt_START_BIT                        12
#define SIGNAL_VCU_HVILClsdFlt_BIT_LEN                          1
#define SIGNAL_VCU_VehOperatingMd_START_BIT                     19
#define SIGNAL_VCU_VehOperatingMd_BIT_LEN                       3
#define SIGNAL_VCU_ChargeFinished_START_BIT                     18
#define SIGNAL_VCU_ChargeFinished_BIT_LEN                       1
#define SIGNAL_VCU_DriveMode_START_BIT                          29
#define SIGNAL_VCU_DriveMode_BIT_LEN                            3
#define SIGNAL_VCU_126_CheckSum_START_BIT                       60
#define SIGNAL_VCU_126_CheckSum_BIT_LEN                         4
#define SIGNAL_VCU_126_RollingCounter_START_BIT                 56
#define SIGNAL_VCU_126_RollingCounter_BIT_LEN                   4
/* Message VCU_128h */
#define MSG_ID_VCU_128h                                         0x128
#define SIGNAL_VCU_VehOdo_START_BIT                             0
#define SIGNAL_VCU_VehOdo_BIT_LEN                               24
#define SIGNAL_VCU_VehAvrgEgyCnse_START_BIT                     24
#define SIGNAL_VCU_VehAvrgEgyCnse_BIT_LEN                       9
#define SIGNAL_VCU_VehRealTEgyCnse_START_BIT                    33
#define SIGNAL_VCU_VehRealTEgyCnse_BIT_LEN                      9
#define SIGNAL_VCU_ResiMilg_START_BIT                           44
#define SIGNAL_VCU_ResiMilg_BIT_LEN                             12
#define SIGNAL_VCU_128_CheckSum_START_BIT                       60
#define SIGNAL_VCU_128_CheckSum_BIT_LEN                         4
#define SIGNAL_VCU_128_RollingCounter_START_BIT                 56
#define SIGNAL_VCU_128_RollingCounter_BIT_LEN                   4
/* Message MCU_130h */
#define MSG_ID_MCU_130h                                         0x130
#define SIGNAL_MCU_MotActuToq_START_BIT                         0
#define SIGNAL_MCU_MotActuToq_BIT_LEN                           16
#define SIGNAL_MCU_MotActuSpd_START_BIT                         16
#define SIGNAL_MCU_MotActuSpd_BIT_LEN                           16
#define SIGNAL_MCU_Sts_START_BIT                                48
#define SIGNAL_MCU_Sts_BIT_LEN                                  3
/* Message MCU_132h */
#define MSG_ID_MCU_132h                                         0x132
#define SIGNAL_MCU_MotActuTem_START_BIT                         0
#define SIGNAL_MCU_MotActuTem_BIT_LEN                           8
#define SIGNAL_MCU_MCUActuTem_START_BIT                         8
#define SIGNAL_MCU_MCUActuTem_BIT_LEN                           8
#define SIGNAL_MCU_MotActuCrnt_START_BIT                        16
#define SIGNAL_MCU_MotActuCrnt_BIT_LEN                          16
#define SIGNAL_MCU_MotActuVol_START_BIT                         32
#define SIGNAL_MCU_MotActuVol_BIT_LEN                           16
#define SIGNAL_MCU_MotErLvl_START_BIT                           53
#define SIGNAL_MCU_MotErLvl_BIT_LEN                             3
#define SIGNAL_MCU_132_CheckSum_START_BIT                       60
#define SIGNAL_MCU_132_CheckSum_BIT_LEN                         4
#define SIGNAL_MCU_132_RollingCounter_START_BIT                 56
#define SIGNAL_MCU_132_RollingCounter_BIT_LEN                   4
/* Message BMS_140h */
#define MSG_ID_BMS_140h                                         0x140
#define SIGNAL_BMS_HVBatErrLvl_START_BIT                        0
#define SIGNAL_BMS_HVBatErrLvl_BIT_LEN                          3
#define SIGNAL_BMS_HVBatFltSts_START_BIT                        15
#define SIGNAL_BMS_HVBatFltSts_BIT_LEN                          1
#define SIGNAL_BMS_InsulationMonitorWarn_START_BIT              21
#define SIGNAL_BMS_InsulationMonitorWarn_BIT_LEN                2
#define SIGNAL_BMS_InsulationResistance_START_BIT               24
#define SIGNAL_BMS_InsulationResistance_BIT_LEN                 16
#define SIGNAL_BMS_140_CheckSum_START_BIT                       60
#define SIGNAL_BMS_140_CheckSum_BIT_LEN                         4
#define SIGNAL_BMS_140_RollingCounter_START_BIT                 56
#define SIGNAL_BMS_140_RollingCounter_BIT_LEN                   4
/* Message BMS_142h */
#define MSG_ID_BMS_142h                                         0x142
#define SIGNAL_BMS_HVBatCellVolDiffSts_START_BIT                6
#define SIGNAL_BMS_HVBatCellVolDiffSts_BIT_LEN                  2
#define SIGNAL_BMS_HVBatCellOverTemSts_START_BIT                4
#define SIGNAL_BMS_HVBatCellOverTemSts_BIT_LEN                  2
#define SIGNAL_BMS_HVBatCellOverVolSts_START_BIT                2
#define SIGNAL_BMS_HVBatCellOverVolSts_BIT_LEN                  2
#define SIGNAL_BMS_HVBatCellUnderVolSts_START_BIT               0
#define SIGNAL_BMS_HVBatCellUnderVolSts_BIT_LEN                 2
#define SIGNAL_BMS_HVBatOverCrntSts_START_BIT                   14
#define SIGNAL_BMS_HVBatOverCrntSts_BIT_LEN                     2
#define SIGNAL_BMS_HVBatOverTem_START_BIT                       13
#define SIGNAL_BMS_HVBatOverTem_BIT_LEN                         1
#define SIGNAL_BMS_HVBatPackOverVolSts_START_BIT                11
#define SIGNAL_BMS_HVBatPackOverVolSts_BIT_LEN                  2
#define SIGNAL_BMS_HVBatPackUnderVolSts_START_BIT               9
#define SIGNAL_BMS_HVBatPackUnderVolSts_BIT_LEN                 2
#define SIGNAL_BMS_SOCLowFlt_START_BIT                          8
#define SIGNAL_BMS_SOCLowFlt_BIT_LEN                            1
#define SIGNAL_BMS_HVBatCellTemOverDiffSts_START_BIT            22
#define SIGNAL_BMS_HVBatCellTemOverDiffSts_BIT_LEN              2
#define SIGNAL_BMS_SOCHighFlt_START_BIT                         21
#define SIGNAL_BMS_SOCHighFlt_BIT_LEN                           1
#define SIGNAL_BMS_SOCJumpFlt_START_BIT                         20
#define SIGNAL_BMS_SOCJumpFlt_BIT_LEN                           1
#define SIGNAL_BMS_BatNotMatchFlt_START_BIT                     19
#define SIGNAL_BMS_BatNotMatchFlt_BIT_LEN                       1
#define SIGNAL_BMS_HVBatCellDiffFalt_START_BIT                  18
#define SIGNAL_BMS_HVBatCellDiffFalt_BIT_LEN                    1
#define SIGNAL_BMS_HVBatRelayFlt_START_BIT                      17
#define SIGNAL_BMS_HVBatRelayFlt_BIT_LEN                        1
#define SIGNAL_BMS_BatOverChg_START_BIT                         16
#define SIGNAL_BMS_BatOverChg_BIT_LEN                           1
#define SIGNAL_BMS_HVBatCellUnderTemSts_START_BIT               30
#define SIGNAL_BMS_HVBatCellUnderTemSts_BIT_LEN                 2
#define SIGNAL_BMS_HVBatUnderTem_START_BIT                      29
#define SIGNAL_BMS_HVBatUnderTem_BIT_LEN                        1
#define SIGNAL_BMS_CANComFlt_START_BIT                          28
#define SIGNAL_BMS_CANComFlt_BIT_LEN                            1
#define SIGNAL_BMS_CANComFltWithLECU_START_BIT                  27
#define SIGNAL_BMS_CANComFltWithLECU_BIT_LEN                    1
#define SIGNAL_BMS_CANComFlt_OBC_START_BIT                      24
#define SIGNAL_BMS_CANComFlt_OBC_BIT_LEN                        1
#define SIGNAL_BMS_FaultCounter_START_BIT                       50
#define SIGNAL_BMS_FaultCounter_BIT_LEN                         6
#define SIGNAL_BMS_142_CheckSum_START_BIT                       60
#define SIGNAL_BMS_142_CheckSum_BIT_LEN                         4
#define SIGNAL_BMS_142_RollingCounter_START_BIT                 56
#define SIGNAL_BMS_142_RollingCounter_BIT_LEN                   4
/* Message BMS_143h */
#define MSG_ID_BMS_143h                                         0x143
#define SIGNAL_BMS_Sts_START_BIT                                0
#define SIGNAL_BMS_Sts_BIT_LEN                                  3
#define SIGNAL_BMS_OBC_Enable_START_BIT                         8
#define SIGNAL_BMS_OBC_Enable_BIT_LEN                           2
#define SIGNAL_BMS_143_CheckSum_START_BIT                       60
#define SIGNAL_BMS_143_CheckSum_BIT_LEN                         4
#define SIGNAL_BMS_143_RollingCounter_START_BIT                 56
#define SIGNAL_BMS_143_RollingCounter_BIT_LEN                   4
/* Message BMS_148h */
#define MSG_ID_BMS_148h                                         0x148
#define SIGNAL_BMS_HVBatCrnt_START_BIT                          0
#define SIGNAL_BMS_HVBatCrnt_BIT_LEN                            16
#define SIGNAL_BMS_HVBatVol_START_BIT                           16
#define SIGNAL_BMS_HVBatVol_BIT_LEN                             16
#define SIGNAL_BMS_HVBatSOC_START_BIT                           40
#define SIGNAL_BMS_HVBatSOC_BIT_LEN                             8
/* Message BMS_160h */
#define MSG_ID_BMS_160h                                         0x160
#define SIGNAL_BMS_HVBatLowestVolCellNum_START_BIT              0
#define SIGNAL_BMS_HVBatLowestVolCellNum_BIT_LEN                8
#define SIGNAL_BMS_HVBatHighestVolCellNum_START_BIT             8
#define SIGNAL_BMS_HVBatHighestVolCellNum_BIT_LEN               8
#define SIGNAL_BMS_HVBatLowestTemCellNum_START_BIT              16
#define SIGNAL_BMS_HVBatLowestTemCellNum_BIT_LEN                8
#define SIGNAL_BMS_HVBatHighestTemCellNum_START_BIT             24
#define SIGNAL_BMS_HVBatHighestTemCellNum_BIT_LEN               8
/* Message BMS_162h */
#define MSG_ID_BMS_162h                                         0x162
#define SIGNAL_BMS_HVBatLowestCellVol_START_BIT                 0
#define SIGNAL_BMS_HVBatLowestCellVol_BIT_LEN                   16
#define SIGNAL_BMS_HVBatHighestCellVol_START_BIT                16
#define SIGNAL_BMS_HVBatHighestCellVol_BIT_LEN                  16
#define SIGNAL_BMS_HVBatHighestTem_START_BIT                    32
#define SIGNAL_BMS_HVBatHighestTem_BIT_LEN                      8
#define SIGNAL_BMS_HVBatLowestTem_START_BIT                     40
#define SIGNAL_BMS_HVBatLowestTem_BIT_LEN                       8
/* Message GW_EGSM_163h */
#define MSG_ID_GW_EGSM_163h                                     0x163
#define SIGNAL_EGSM_ParkSwitch_START_BIT                        3
#define SIGNAL_EGSM_ParkSwitch_BIT_LEN                          1
#define SIGNAL_EGSM_ParkSwitchInvalid_START_BIT                 2
#define SIGNAL_EGSM_ParkSwitchInvalid_BIT_LEN                   1
#define SIGNAL_EGSM_DrivingMode_START_BIT                       13
#define SIGNAL_EGSM_DrivingMode_BIT_LEN                         3
#define SIGNAL_EGSM_FaultLevel_START_BIT                        11
#define SIGNAL_EGSM_FaultLevel_BIT_LEN                          2
#define SIGNAL_EGSM_Illume_Fail_START_BIT                       23
#define SIGNAL_EGSM_Illume_Fail_BIT_LEN                         1
#define SIGNAL_EGSM_GearPosition_CheckSum_START_BIT             60
#define SIGNAL_EGSM_GearPosition_CheckSum_BIT_LEN               4
#define SIGNAL_EGSM_GearPosition_RollingCounter_START_BIT       56
#define SIGNAL_EGSM_GearPosition_RollingCounter_BIT_LEN         4
/* Message BMS_164h */
#define MSG_ID_BMS_164h                                         0x164
#define SIGNAL_BMS_HVBatCellVol_No1_START_BIT                   0
#define SIGNAL_BMS_HVBatCellVol_No1_BIT_LEN                     16
#define SIGNAL_BMS_HVBatCellVol_No2_START_BIT                   16
#define SIGNAL_BMS_HVBatCellVol_No2_BIT_LEN                     16
#define SIGNAL_BMS_HVBatCellVol_No3_START_BIT                   32
#define SIGNAL_BMS_HVBatCellVol_No3_BIT_LEN                     16
#define SIGNAL_BMS_HVBatCellVol_No4_START_BIT                   48
#define SIGNAL_BMS_HVBatCellVol_No4_BIT_LEN                     16
/* Message BMS_166h */
#define MSG_ID_BMS_166h                                         0x166
#define SIGNAL_BMS_HVBatCellVol_No5_START_BIT                   0
#define SIGNAL_BMS_HVBatCellVol_No5_BIT_LEN                     16
#define SIGNAL_BMS_HVBatCellVol_No6_START_BIT                   16
#define SIGNAL_BMS_HVBatCellVol_No6_BIT_LEN                     16
#define SIGNAL_BMS_HVBatCellVol_No7_START_BIT                   32
#define SIGNAL_BMS_HVBatCellVol_No7_BIT_LEN                     16
#define SIGNAL_BMS_HVBatCellVol_No8_START_BIT                   48
#define SIGNAL_BMS_HVBatCellVol_No8_BIT_LEN                     16
/* Message BMS_168h */
#define MSG_ID_BMS_168h                                         0x168
#define SIGNAL_BMS_HVBatCellVol_No9_START_BIT                   0
#define SIGNAL_BMS_HVBatCellVol_No9_BIT_LEN                     16
#define SIGNAL_BMS_HVBatCellVol_No10_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No10_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No11_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No11_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No12_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No12_BIT_LEN                    16
/* Message BMS_170h */
#define MSG_ID_BMS_170h                                         0x170
#define SIGNAL_BMS_HVBatCellVol_No13_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No13_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No14_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No14_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No15_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No15_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No16_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No16_BIT_LEN                    16
/* Message DCDC_171h */
#define MSG_ID_DCDC_171h                                        0x171
#define SIGNAL_DCDC_StsErrLvl_START_BIT                         5
#define SIGNAL_DCDC_StsErrLvl_BIT_LEN                           3
#define SIGNAL_DCDC_Md_START_BIT                                2
#define SIGNAL_DCDC_Md_BIT_LEN                                  3
#define SIGNAL_DCDC_TemFlt_START_BIT                            1
#define SIGNAL_DCDC_TemFlt_BIT_LEN                              1
/* Message BMS_172h */
#define MSG_ID_BMS_172h                                         0x172
#define SIGNAL_BMS_HVBatCellVol_No17_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No17_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No18_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No18_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No19_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No19_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No20_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No20_BIT_LEN                    16
/* Message BMS_174h */
#define MSG_ID_BMS_174h                                         0x174
#define SIGNAL_BMS_HVBatCellVol_No21_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No21_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No22_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No22_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No23_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No23_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No24_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No24_BIT_LEN                    16
/* Message BMS_176h */
#define MSG_ID_BMS_176h                                         0x176
#define SIGNAL_BMS_HVBatCellVol_No25_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No25_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No26_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No26_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No27_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No27_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No28_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No28_BIT_LEN                    16
/* Message BMS_178h */
#define MSG_ID_BMS_178h                                         0x178
#define SIGNAL_BMS_HVBatCellVol_No29_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No29_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No30_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No30_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No31_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No31_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No32_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No32_BIT_LEN                    16
/* Message BMS_180h */
#define MSG_ID_BMS_180h                                         0x180
#define SIGNAL_BMS_HVBatCellVol_No33_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No33_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No34_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No34_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No35_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No35_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No36_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No36_BIT_LEN                    16
/* Message MCU_181h */
#define MSG_ID_MCU_181h                                         0x181
#define SIGNAL_MCU_PwrModuFlt_START_BIT                         7
#define SIGNAL_MCU_PwrModuFlt_BIT_LEN                           1
#define SIGNAL_MCU_MotOverVol_START_BIT                         6
#define SIGNAL_MCU_MotOverVol_BIT_LEN                           1
#define SIGNAL_MCU_MotOverCrnt_START_BIT                        5
#define SIGNAL_MCU_MotOverCrnt_BIT_LEN                          1
#define SIGNAL_MCU_IGBOverTem_START_BIT                         4
#define SIGNAL_MCU_IGBOverTem_BIT_LEN                           1
#define SIGNAL_MCU_MotOverTem_START_BIT                         3
#define SIGNAL_MCU_MotOverTem_BIT_LEN                           1
#define SIGNAL_MCU_CANComFlt_START_BIT                          2
#define SIGNAL_MCU_CANComFlt_BIT_LEN                            1
#define SIGNAL_MCU_DschrgFlt_START_BIT                          1
#define SIGNAL_MCU_DschrgFlt_BIT_LEN                            1
#define SIGNAL_MCU_PrchrgrFlt_START_BIT                         0
#define SIGNAL_MCU_PrchrgrFlt_BIT_LEN                           1
#define SIGNAL_MCU_EEPROMFlt_START_BIT                          15
#define SIGNAL_MCU_EEPROMFlt_BIT_LEN                            1
#define SIGNAL_MCU_MotUnderVol_START_BIT                        14
#define SIGNAL_MCU_MotUnderVol_BIT_LEN                          1
#define SIGNAL_MCU_MotRsovrFlt_START_BIT                        13
#define SIGNAL_MCU_MotRsovrFlt_BIT_LEN                          1
#define SIGNAL_MCU_MotOverSpd_START_BIT                         12
#define SIGNAL_MCU_MotOverSpd_BIT_LEN                           1
#define SIGNAL_MCU_SelfCheckFlt_START_BIT                       11
#define SIGNAL_MCU_SelfCheckFlt_BIT_LEN                         1
#define SIGNAL_MCU_IGBTTemSnsrFlt_START_BIT                     10
#define SIGNAL_MCU_IGBTTemSnsrFlt_BIT_LEN                       1
#define SIGNAL_MCU_MotTemSnsrFlt_START_BIT                      9
#define SIGNAL_MCU_MotTemSnsrFlt_BIT_LEN                        1
#define SIGNAL_MCU_CrntSnsrFlt_START_BIT                        8
#define SIGNAL_MCU_CrntSnsrFlt_BIT_LEN                          1
#define SIGNAL_MCU_OverloadrFlt_START_BIT                       23
#define SIGNAL_MCU_OverloadrFlt_BIT_LEN                         1
#define SIGNAL_MCU_12VLowVolFlt_START_BIT                       22
#define SIGNAL_MCU_12VLowVolFlt_BIT_LEN                         1
#define SIGNAL_MCU_MotRotBlockFlt_START_BIT                     21
#define SIGNAL_MCU_MotRotBlockFlt_BIT_LEN                       1
#define SIGNAL_MCU_MotLackOfPhaFlt_START_BIT                    20
#define SIGNAL_MCU_MotLackOfPhaFlt_BIT_LEN                      1
#define SIGNAL_MCU_InvldInfoFromVCU_START_BIT                   19
#define SIGNAL_MCU_InvldInfoFromVCU_BIT_LEN                     1
#define SIGNAL_MCU_OverTemWrnng_START_BIT                       18
#define SIGNAL_MCU_OverTemWrnng_BIT_LEN                         1
#define SIGNAL_MCU_ElecMotOverTemWrnng_START_BIT                17
#define SIGNAL_MCU_ElecMotOverTemWrnng_BIT_LEN                  1
#define SIGNAL_MCU_ElecMotOverSpdWrnng_START_BIT                16
#define SIGNAL_MCU_ElecMotOverSpdWrnng_BIT_LEN                  1
#define SIGNAL_MCU_DcUOverVWanng_START_BIT                      31
#define SIGNAL_MCU_DcUOverVWanng_BIT_LEN                        1
#define SIGNAL_MCU_DcUUnderVWanng_START_BIT                     30
#define SIGNAL_MCU_DcUUnderVWanng_BIT_LEN                       1
#define SIGNAL_MCU_ModErr_START_BIT                             29
#define SIGNAL_MCU_ModErr_BIT_LEN                               1
#define SIGNAL_MCU_CoolntTem_START_BIT                          32
#define SIGNAL_MCU_CoolntTem_BIT_LEN                            8
#define SIGNAL_MCU_FaultCounter_START_BIT                       50
#define SIGNAL_MCU_FaultCounter_BIT_LEN                         6
#define SIGNAL_MCU_181_CheckSum_START_BIT                       60
#define SIGNAL_MCU_181_CheckSum_BIT_LEN                         4
#define SIGNAL_MCU_181_RollingCounter_START_BIT                 56
#define SIGNAL_MCU_181_RollingCounter_BIT_LEN                   4
/* Message BMS_182h */
#define MSG_ID_BMS_182h                                         0x182
#define SIGNAL_BMS_HVBatCellVol_No37_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No37_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No38_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No38_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No39_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No39_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No40_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No40_BIT_LEN                    16
/* Message OBC_183h */
#define MSG_ID_OBC_183h                                         0x183
#define SIGNAL_OBC_StsErrLvl_START_BIT                          4
#define SIGNAL_OBC_StsErrLvl_BIT_LEN                            2
#define SIGNAL_ChargerHardwareFault_START_BIT                   2
#define SIGNAL_ChargerHardwareFault_BIT_LEN                     1
#define SIGNAL_ChargerOTP_START_BIT                             1
#define SIGNAL_ChargerOTP_BIT_LEN                               1
#define SIGNAL_ChargerACVoltageFault_START_BIT                  0
#define SIGNAL_ChargerACVoltageFault_BIT_LEN                    1
#define SIGNAL_ChargerCommunicationFault_START_BIT              14
#define SIGNAL_ChargerCommunicationFault_BIT_LEN                1
#define SIGNAL_ChargerConnectFault_START_BIT                    13
#define SIGNAL_ChargerConnectFault_BIT_LEN                      1
#define SIGNAL_OBC_183_CheckSum_START_BIT                       60
#define SIGNAL_OBC_183_CheckSum_BIT_LEN                         4
#define SIGNAL_OBC_183_RollingCounter_START_BIT                 56
#define SIGNAL_OBC_183_RollingCounter_BIT_LEN                   4
/* Message BMS_184h */
#define MSG_ID_BMS_184h                                         0x184
#define SIGNAL_BMS_HVBatCellVol_No41_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No41_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No42_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No42_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No43_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No43_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No44_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No44_BIT_LEN                    16
/* Message BMS_186h */
#define MSG_ID_BMS_186h                                         0x186
#define SIGNAL_BMS_HVBatCellVol_No45_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No45_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No46_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No46_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No47_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No47_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No48_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No48_BIT_LEN                    16
/* Message BMS_188h */
#define MSG_ID_BMS_188h                                         0x188
#define SIGNAL_BMS_HVBatCellVol_No49_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No49_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No50_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No50_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No51_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No51_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No52_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No52_BIT_LEN                    16
/* Message BMS_190h */
#define MSG_ID_BMS_190h                                         0x190
#define SIGNAL_BMS_HVBatCellVol_No53_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No53_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No54_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No54_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No55_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No55_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No56_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No56_BIT_LEN                    16
/* Message BMS_192h */
#define MSG_ID_BMS_192h                                         0x192
#define SIGNAL_BMS_HVBatCellVol_No57_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No57_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No58_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No58_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No59_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No59_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No60_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No60_BIT_LEN                    16
/* Message BMS_194h */
#define MSG_ID_BMS_194h                                         0x194
#define SIGNAL_BMS_HVBatCellVol_No61_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No61_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No62_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No62_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No63_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No63_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No64_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No64_BIT_LEN                    16
/* Message BMS_196h */
#define MSG_ID_BMS_196h                                         0x196
#define SIGNAL_BMS_HVBatCellVol_No65_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No65_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No66_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No66_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No67_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No67_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No68_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No68_BIT_LEN                    16
/* Message BMS_198h */
#define MSG_ID_BMS_198h                                         0x198
#define SIGNAL_BMS_HVBatCellVol_No69_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No69_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No70_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No70_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No71_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No71_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No72_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No72_BIT_LEN                    16
/* Message BMS_1A0h */
#define MSG_ID_BMS_1A0h                                         0x1A0
#define SIGNAL_BMS_HVBatCellVol_No73_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No73_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No74_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No74_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No75_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No75_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No76_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No76_BIT_LEN                    16
/* Message BMS_1A2h */
#define MSG_ID_BMS_1A2h                                         0x1A2
#define SIGNAL_BMS_HVBatCellVol_No77_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No77_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No78_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No78_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No79_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No79_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No80_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No80_BIT_LEN                    16
/* Message BMS_1A4h */
#define MSG_ID_BMS_1A4h                                         0x1A4
#define SIGNAL_BMS_HVBatCellVol_No81_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No81_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No82_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No82_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No83_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No83_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No84_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No84_BIT_LEN                    16
/* Message BMS_1A6h */
#define MSG_ID_BMS_1A6h                                         0x1A6
#define SIGNAL_BMS_HVBatCellVol_No85_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No85_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No86_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No86_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No87_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No87_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No88_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No88_BIT_LEN                    16
/* Message BMS_1A8h */
#define MSG_ID_BMS_1A8h                                         0x1A8
#define SIGNAL_BMS_HVBatCellVol_No89_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No89_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No90_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No90_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No91_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No91_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No92_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No92_BIT_LEN                    16
/* Message BMS_1A9h */
#define MSG_ID_BMS_1A9h                                         0x1A9
#define SIGNAL_BMS_HVBatCellVol_No93_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No93_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No94_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No94_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No95_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No95_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No96_START_BIT                  48
#define SIGNAL_BMS_HVBatCellVol_No96_BIT_LEN                    16
/* Message BMS_1AAh */
#define MSG_ID_BMS_1AAh                                         0x1AA
#define SIGNAL_BMS_HVBatCellVol_No97_START_BIT                  0
#define SIGNAL_BMS_HVBatCellVol_No97_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No98_START_BIT                  16
#define SIGNAL_BMS_HVBatCellVol_No98_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No99_START_BIT                  32
#define SIGNAL_BMS_HVBatCellVol_No99_BIT_LEN                    16
#define SIGNAL_BMS_HVBatCellVol_No100_START_BIT                 48
#define SIGNAL_BMS_HVBatCellVol_No100_BIT_LEN                   16
/* Message BMS_1ABh */
#define MSG_ID_BMS_1ABh                                         0x1AB
#define SIGNAL_BMS_HVBatCellVol_No101_START_BIT                 0
#define SIGNAL_BMS_HVBatCellVol_No101_BIT_LEN                   16
#define SIGNAL_BMS_HVBatCellVol_No102_START_BIT                 16
#define SIGNAL_BMS_HVBatCellVol_No102_BIT_LEN                   16
#define SIGNAL_BMS_HVBatCellVol_No103_START_BIT                 32
#define SIGNAL_BMS_HVBatCellVol_No103_BIT_LEN                   16
#define SIGNAL_BMS_HVBatCellVol_No104_START_BIT                 48
#define SIGNAL_BMS_HVBatCellVol_No104_BIT_LEN                   16
/* Message BMS_1ACh */
#define MSG_ID_BMS_1ACh                                         0x1AC
#define SIGNAL_BMS_HVBatCellVol_No105_START_BIT                 0
#define SIGNAL_BMS_HVBatCellVol_No105_BIT_LEN                   16
#define SIGNAL_BMS_HVBatCellVol_No106_START_BIT                 16
#define SIGNAL_BMS_HVBatCellVol_No106_BIT_LEN                   16
#define SIGNAL_BMS_HVBatCellVol_No107_START_BIT                 32
#define SIGNAL_BMS_HVBatCellVol_No107_BIT_LEN                   16
#define SIGNAL_BMS_HVBatCellVol_No108_START_BIT                 48
#define SIGNAL_BMS_HVBatCellVol_No108_BIT_LEN                   16
/* Message BMS_1ADh */
#define MSG_ID_BMS_1ADh                                         0x1AD
#define SIGNAL_BMS_HVBatCellVol_No109_START_BIT                 0
#define SIGNAL_BMS_HVBatCellVol_No109_BIT_LEN                   16
#define SIGNAL_BMS_HVBatCellVol_No110_START_BIT                 16
#define SIGNAL_BMS_HVBatCellVol_No110_BIT_LEN                   16
#define SIGNAL_BMS_HVBatCellVol_No111_START_BIT                 32
#define SIGNAL_BMS_HVBatCellVol_No111_BIT_LEN                   16
#define SIGNAL_BMS_HVBatCellVol_No112_START_BIT                 48
#define SIGNAL_BMS_HVBatCellVol_No112_BIT_LEN                   16
/* Message BMS_1AEh */
#define MSG_ID_BMS_1AEh                                         0x1AE
#define SIGNAL_BMS_HVBatCellVol_No113_START_BIT                 0
#define SIGNAL_BMS_HVBatCellVol_No113_BIT_LEN                   16
#define SIGNAL_BMS_HVBatCellVol_No114_START_BIT                 16
#define SIGNAL_BMS_HVBatCellVol_No114_BIT_LEN                   16
#define SIGNAL_BMS_HVBatCellVol_No115_START_BIT                 32
#define SIGNAL_BMS_HVBatCellVol_No115_BIT_LEN                   16
#define SIGNAL_BMS_HVBatCellVol_No116_START_BIT                 48
#define SIGNAL_BMS_HVBatCellVol_No116_BIT_LEN                   16
/* Message BMS_1AFh */
#define MSG_ID_BMS_1AFh                                         0x1AF
#define SIGNAL_BMS_HVBatCellVol_No117_START_BIT                 0
#define SIGNAL_BMS_HVBatCellVol_No117_BIT_LEN                   16
#define SIGNAL_BMS_HVBatCellVol_No118_START_BIT                 16
#define SIGNAL_BMS_HVBatCellVol_No118_BIT_LEN                   16
#define SIGNAL_BMS_HVBatCellVol_No119_START_BIT                 32
#define SIGNAL_BMS_HVBatCellVol_No119_BIT_LEN                   16
#define SIGNAL_BMS_HVBatCellVol_No120_START_BIT                 48
#define SIGNAL_BMS_HVBatCellVol_No120_BIT_LEN                   16
/* Message BMS_1B0h */
#define MSG_ID_BMS_1B0h                                         0x1B0
#define SIGNAL_BMS_HVBatCellTem_No1_START_BIT                   0
#define SIGNAL_BMS_HVBatCellTem_No1_BIT_LEN                     8
#define SIGNAL_BMS_HVBatCellTem_No2_START_BIT                   8
#define SIGNAL_BMS_HVBatCellTem_No2_BIT_LEN                     8
#define SIGNAL_BMS_HVBatCellTem_No3_START_BIT                   16
#define SIGNAL_BMS_HVBatCellTem_No3_BIT_LEN                     8
#define SIGNAL_BMS_HVBatCellTem_No4_START_BIT                   24
#define SIGNAL_BMS_HVBatCellTem_No4_BIT_LEN                     8
#define SIGNAL_BMS_HVBatCellTem_No5_START_BIT                   32
#define SIGNAL_BMS_HVBatCellTem_No5_BIT_LEN                     8
#define SIGNAL_BMS_HVBatCellTem_No6_START_BIT                   40
#define SIGNAL_BMS_HVBatCellTem_No6_BIT_LEN                     8
#define SIGNAL_BMS_HVBatCellTem_No7_START_BIT                   48
#define SIGNAL_BMS_HVBatCellTem_No7_BIT_LEN                     8
#define SIGNAL_BMS_HVBatCellTem_No8_START_BIT                   56
#define SIGNAL_BMS_HVBatCellTem_No8_BIT_LEN                     8
/* Message BMS_1B2h */
#define MSG_ID_BMS_1B2h                                         0x1B2
#define SIGNAL_BMS_HVBatCellTem_No9_START_BIT                   0
#define SIGNAL_BMS_HVBatCellTem_No9_BIT_LEN                     8
#define SIGNAL_BMS_HVBatCellTem_No10_START_BIT                  8
#define SIGNAL_BMS_HVBatCellTem_No10_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No11_START_BIT                  16
#define SIGNAL_BMS_HVBatCellTem_No11_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No12_START_BIT                  24
#define SIGNAL_BMS_HVBatCellTem_No12_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No13_START_BIT                  32
#define SIGNAL_BMS_HVBatCellTem_No13_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No14_START_BIT                  40
#define SIGNAL_BMS_HVBatCellTem_No14_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No15_START_BIT                  48
#define SIGNAL_BMS_HVBatCellTem_No15_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No16_START_BIT                  56
#define SIGNAL_BMS_HVBatCellTem_No16_BIT_LEN                    8
/* Message BMS_1B4h */
#define MSG_ID_BMS_1B4h                                         0x1B4
#define SIGNAL_BMS_HVBatCellTem_No17_START_BIT                  0
#define SIGNAL_BMS_HVBatCellTem_No17_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No18_START_BIT                  8
#define SIGNAL_BMS_HVBatCellTem_No18_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No19_START_BIT                  16
#define SIGNAL_BMS_HVBatCellTem_No19_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No20_START_BIT                  24
#define SIGNAL_BMS_HVBatCellTem_No20_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No21_START_BIT                  32
#define SIGNAL_BMS_HVBatCellTem_No21_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No22_START_BIT                  40
#define SIGNAL_BMS_HVBatCellTem_No22_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No23_START_BIT                  48
#define SIGNAL_BMS_HVBatCellTem_No23_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No24_START_BIT                  56
#define SIGNAL_BMS_HVBatCellTem_No24_BIT_LEN                    8
/* Message BMS_1B6h */
#define MSG_ID_BMS_1B6h                                         0x1B6
#define SIGNAL_BMS_HVBatCellTem_No25_START_BIT                  0
#define SIGNAL_BMS_HVBatCellTem_No25_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No26_START_BIT                  8
#define SIGNAL_BMS_HVBatCellTem_No26_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No27_START_BIT                  16
#define SIGNAL_BMS_HVBatCellTem_No27_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No28_START_BIT                  24
#define SIGNAL_BMS_HVBatCellTem_No28_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No29_START_BIT                  32
#define SIGNAL_BMS_HVBatCellTem_No29_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No30_START_BIT                  40
#define SIGNAL_BMS_HVBatCellTem_No30_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No31_START_BIT                  48
#define SIGNAL_BMS_HVBatCellTem_No31_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No32_START_BIT                  56
#define SIGNAL_BMS_HVBatCellTem_No32_BIT_LEN                    8
/* Message BMS_1B8h */
#define MSG_ID_BMS_1B8h                                         0x1B8
#define SIGNAL_BMS_HVBatCellTem_No33_START_BIT                  0
#define SIGNAL_BMS_HVBatCellTem_No33_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No34_START_BIT                  8
#define SIGNAL_BMS_HVBatCellTem_No34_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No35_START_BIT                  16
#define SIGNAL_BMS_HVBatCellTem_No35_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No36_START_BIT                  24
#define SIGNAL_BMS_HVBatCellTem_No36_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No37_START_BIT                  32
#define SIGNAL_BMS_HVBatCellTem_No37_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No38_START_BIT                  40
#define SIGNAL_BMS_HVBatCellTem_No38_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No39_START_BIT                  48
#define SIGNAL_BMS_HVBatCellTem_No39_BIT_LEN                    8
#define SIGNAL_BMS_HVBatCellTem_No40_START_BIT                  56
#define SIGNAL_BMS_HVBatCellTem_No40_BIT_LEN                    8
/* Message VCU_620h */
#define MSG_ID_VCU_620h                                         0x620
#define MSG_VCU_620h_START_BIT                                  0
#define MSG_VCU_620h_BIT_LEN                                    64
#define SIGNAL_CAN_BUS_FAULT_START_BIT                          7
#define SIGNAL_CAN_BUS_FAULT_BIT_LEN                            1
#define SIGNAL_MCU_CAN_RX_FAILED_START_BIT                      6
#define SIGNAL_MCU_CAN_RX_FAILED_BIT_LEN                        1
#define SIGNAL_BMS_CAN_RX_FAILED_START_BIT                      5
#define SIGNAL_BMS_CAN_RX_FAILED_BIT_LEN                        1
#define SIGNAL_ABS_CAN_RX_FAILED_START_BIT                      4
#define SIGNAL_ABS_CAN_RX_FAILED_BIT_LEN                        1
#define SIGNAL_CLM_CAN_RX_FAILED_START_BIT                      3
#define SIGNAL_CLM_CAN_RX_FAILED_BIT_LEN                        1
#define SIGNAL_ETC_CAN_RX_FAILED_START_BIT                      2
#define SIGNAL_ETC_CAN_RX_FAILED_BIT_LEN                        1
#define SIGNAL_TBOX_CAN_RX_FAILED_START_BIT                     1
#define SIGNAL_TBOX_CAN_RX_FAILED_BIT_LEN                       1
#define SIGNAL_DCDC_CAN_RX_FAILED_START_BIT                     0
#define SIGNAL_DCDC_CAN_RX_FAILED_BIT_LEN                       1
#define SIGNAL_PEPS_CAN_RX_FAILED_START_BIT                     15
#define SIGNAL_PEPS_CAN_RX_FAILED_BIT_LEN                       1
#define SIGNAL_GEARPOSITION_FAULT_START_BIT                     14
#define SIGNAL_GEARPOSITION_FAULT_BIT_LEN                       1
#define SIGNAL_PEDAL1_LOW_FAULT_START_BIT                       13
#define SIGNAL_PEDAL1_LOW_FAULT_BIT_LEN                         1
#define SIGNAL_PEDAL1_HIGH_FAULT_START_BIT                      12
#define SIGNAL_PEDAL1_HIGH_FAULT_BIT_LEN                        1
#define SIGNAL_PEDAL2_LOW_FAULT_START_BIT                       11
#define SIGNAL_PEDAL2_LOW_FAULT_BIT_LEN                         1
#define SIGNAL_PEDAL2_HIGH_FAULT_START_BIT                      10
#define SIGNAL_PEDAL2_HIGH_FAULT_BIT_LEN                        1
#define SIGNAL_PEDAL1_PEDAL2_SYN_FAULT_START_BIT                9
#define SIGNAL_PEDAL1_PEDAL2_SYN_FAULT_BIT_LEN                  1
#define SIGNAL_SENSOR_SUPPLY1_5V_FAULT_START_BIT                8
#define SIGNAL_SENSOR_SUPPLY1_5V_FAULT_BIT_LEN                  1
#define SIGNAL_SENSOR_SUPPLY2_5V_FAULT_START_BIT                23
#define SIGNAL_SENSOR_SUPPLY2_5V_FAULT_BIT_LEN                  1
#define SIGNAL_VAC_SENS_OC_SC_START_BIT                         22
#define SIGNAL_VAC_SENS_OC_SC_BIT_LEN                           1
#define SIGNAL_VAC_SENS_IMPLAUSIBLE_START_BIT                   21
#define SIGNAL_VAC_SENS_IMPLAUSIBLE_BIT_LEN                     1
#define SIGNAL_DCDC_CHARGE_FAULT_START_BIT                      20
#define SIGNAL_DCDC_CHARGE_FAULT_BIT_LEN                        1
#define SIGNAL_LV_BATT_VOLTAGE_FAULT_START_BIT                  19
#define SIGNAL_LV_BATT_VOLTAGE_FAULT_BIT_LEN                    1
#define SIGNAL_BRAKE_SWITCH_FAULT_START_BIT                     18
#define SIGNAL_BRAKE_SWITCH_FAULT_BIT_LEN                       1
#define SIGNAL_VEHICLE_SPEED_IMPLAUSIBLE_START_BIT              17
#define SIGNAL_VEHICLE_SPEED_IMPLAUSIBLE_BIT_LEN                1
#define SIGNAL_DCCHRG_NEG_TEMP_FAULT_START_BIT                  16
#define SIGNAL_DCCHRG_NEG_TEMP_FAULT_BIT_LEN                    1
#define SIGNAL_CLM_COMPRESSOR_FAULT_START_BIT                   31
#define SIGNAL_CLM_COMPRESSOR_FAULT_BIT_LEN                     1
#define SIGNAL_CRASH_IMPLAUSIBLE_START_BIT                      30
#define SIGNAL_CRASH_IMPLAUSIBLE_BIT_LEN                        1
#define SIGNAL_L1_MOTOR_TQ_CHECK_ERROR_START_BIT                29
#define SIGNAL_L1_MOTOR_TQ_CHECK_ERROR_BIT_LEN                  1
#define SIGNAL_L1_MOTOR_MODE_CHECK_ERROR_START_BIT              28
#define SIGNAL_L1_MOTOR_MODE_CHECK_ERROR_BIT_LEN                1
#define SIGNAL_MOTOR_BLOCK_WARNING_START_BIT                    27
#define SIGNAL_MOTOR_BLOCK_WARNING_BIT_LEN                      1
#define SIGNAL_MCU_HVIL_FAULT_START_BIT                         26
#define SIGNAL_MCU_HVIL_FAULT_BIT_LEN                           1
#define SIGNAL_BMS_HVIL_FAULT_START_BIT                         25
#define SIGNAL_BMS_HVIL_FAULT_BIT_LEN                           1
#define SIGNAL_VCU_HVIL_INPUT_FAULT_START_BIT                   24
#define SIGNAL_VCU_HVIL_INPUT_FAULT_BIT_LEN                     1
#define SIGNAL_VCU_HVIL_DRIVE_FAULT_START_BIT                   39
#define SIGNAL_VCU_HVIL_DRIVE_FAULT_BIT_LEN                     1
#define SIGNAL_VAC_PUMP_DRIVE_FAULT_START_BIT                   38
#define SIGNAL_VAC_PUMP_DRIVE_FAULT_BIT_LEN                     1
#define SIGNAL_COOLINGPUMP_DRIVE_FAULT_START_BIT                37
#define SIGNAL_COOLINGPUMP_DRIVE_FAULT_BIT_LEN                  1
#define SIGNAL_REVERSELAMP_DRIVE_FAULT_START_BIT                36
#define SIGNAL_REVERSELAMP_DRIVE_FAULT_BIT_LEN                  1
#define SIGNAL_LOWCOOLINGFAN_DRIVE_FAULT_START_BIT              35
#define SIGNAL_LOWCOOLINGFAN_DRIVE_FAULT_BIT_LEN                1
#define SIGNAL_INVERTER_DRIVE_FAULT_START_BIT                   34
#define SIGNAL_INVERTER_DRIVE_FAULT_BIT_LEN                     1
#define SIGNAL_BATTERY_ENABLE_DRIVE_FAULT_START_BIT             33
#define SIGNAL_BATTERY_ENABLE_DRIVE_FAULT_BIT_LEN               1
#define SIGNAL_HIGHCOOLINGFAN_DRIVE_FAULT_START_BIT             32
#define SIGNAL_HIGHCOOLINGFAN_DRIVE_FAULT_BIT_LEN               1
#define SIGNAL_PTC_DRIVE_FAULT_START_BIT                        47
#define SIGNAL_PTC_DRIVE_FAULT_BIT_LEN                          1
#define SIGNAL_MAINCONTRELAY_DRIVE_FAULT_START_BIT              46
#define SIGNAL_MAINCONTRELAY_DRIVE_FAULT_BIT_LEN                1
#define SIGNAL_GEAR_N_LOCK_DRIVE_FAULT_START_BIT                45
#define SIGNAL_GEAR_N_LOCK_DRIVE_FAULT_BIT_LEN                  1
#define SIGNAL_UNEXPECTED_INTERRUPT_START_BIT                   44
#define SIGNAL_UNEXPECTED_INTERRUPT_BIT_LEN                     1
#define SIGNAL_FMEM_FAILED_START_BIT                            43
#define SIGNAL_FMEM_FAILED_BIT_LEN                              1
#define SIGNAL_APP_OVERRUN_START_BIT                            42
#define SIGNAL_APP_OVERRUN_BIT_LEN                              1
#define SIGNAL_VMS_POWER_MOSFET_SC_START_BIT                    41
#define SIGNAL_VMS_POWER_MOSFET_SC_BIT_LEN                      1
#define SIGNAL_SW_WATCHDOG_OCCURED_START_BIT                    40
#define SIGNAL_SW_WATCHDOG_OCCURED_BIT_LEN                      1
#define SIGNAL_MCU_WARNING_ERRLVL_START_BIT                     55
#define SIGNAL_MCU_WARNING_ERRLVL_BIT_LEN                       1
#define SIGNAL_MCU_DISABLE_ERRLVL_START_BIT                     54
#define SIGNAL_MCU_DISABLE_ERRLVL_BIT_LEN                       1
#define SIGNAL_MCU_SHUTDOWN_ERRLVL_START_BIT                    53
#define SIGNAL_MCU_SHUTDOWN_ERRLVL_BIT_LEN                      1
#define SIGNAL_BMS_SERVICE_ERRLVL_START_BIT                     52
#define SIGNAL_BMS_SERVICE_ERRLVL_BIT_LEN                       1
#define SIGNAL_BMS_WARNING_ERRLVL_START_BIT                     51
#define SIGNAL_BMS_WARNING_ERRLVL_BIT_LEN                       1
#define SIGNAL_BMS_INHIBIT_ERRLVL_START_BIT                     50
#define SIGNAL_BMS_INHIBIT_ERRLVL_BIT_LEN                       1
#define SIGNAL_BMS_SHUTDOWN_ERRLVL_START_BIT                    49
#define SIGNAL_BMS_SHUTDOWN_ERRLVL_BIT_LEN                      1
#define SIGNAL_DCDC_WARNING_ERRLVL_START_BIT                    48
#define SIGNAL_DCDC_WARNING_ERRLVL_BIT_LEN                      1
#define SIGNAL_DCDC_DISABLE_ERRLVL_START_BIT                    63
#define SIGNAL_DCDC_DISABLE_ERRLVL_BIT_LEN                      1
#define SIGNAL_DCDC_SHUTDOWN_ERRLVL_START_BIT                   62
#define SIGNAL_DCDC_SHUTDOWN_ERRLVL_BIT_LEN                     1
#define SIGNAL_IMMO_SECURITY_FAILED_START_BIT                   61
#define SIGNAL_IMMO_SECURITY_FAILED_BIT_LEN                     1
#define SIGNAL_IMMO_PIN_UNINITIALISED_FA_START_BIT              60
#define SIGNAL_IMMO_PIN_UNINITIALISED_FA_BIT_LEN                1
/* Message VCU_623h */
#define MSG_ID_VCU_623h                                         0x623
#define MSG_VCU_623h_START_BIT                                  0
#define MSG_VCU_623h_BIT_LEN                                    64

#define CAN1_MSG_ID_NUM                                         52

#define CAN1_MSG_ID_LIST 0x118, 0x126, 0x128, 0x130, 0x132, 0x140, 0x142, 0x143, 0x148, 0x160, 0x162, 0x163, 0x164, 0x166, 0x168, 0x170, 0x171, 0x172, 0x174, 0x176, 0x178, 0x180, 0x181, 0x182, 0x183, 0x184, 0x186, 0x188, 0x190, 0x192, 0x194, 0x196, 0x198, 0x1A0, 0x1A2, 0x1A4, 0x1A6, 0x1A8, 0x1A9, 0x1AA, 0x1AB, 0x1AC, 0x1AD, 0x1AE, 0x1AF, 0x1B0, 0x1B2, 0x1B4, 0x1B6, 0x1B8, 0x620, 0x623
/** @} */ /* CAN1 messages. */

#endif /* __GEN_CAN_MATRIX_H__ */
