/**
 * @file   gen_downstream.h
 * @author Auto generated
 * @note   Created on 2022/05/19 
 */

#ifndef __GEN_DOWNSTREAM_H__
#define __GEN_DOWNSTREAM_H__

/******************************************************************************
 * Definitions
 ******************************************************************************/
/* DOOR_CTRL */
#define DOOR_CTRL_ID                                            0x0001
#define DOOR_CTRL_LEN                                           2
#define REMOTE_DOOR_LOCK_VALID_START_BIT                        63
#define REMOTE_DOOR_LOCK_VALID_BIT_LEN                          1
#define REMOTE_DOOR_LOCK_START_BIT                              53
#define REMOTE_DOOR_LOCK_BIT_LEN                                3
/* SEAT_CTRL */
#define SEAT_CTRL_ID                                            0x0002
#define SEAT_CTRL_LEN                                           2
#define SEAT_WARM_VALID_START_BIT                               63
#define SEAT_WARM_VALID_BIT_LEN                                 1
#define SEAT_AIR_VALID_START_BIT                                62
#define SEAT_AIR_VALID_BIT_LEN                                  1
#define SEAT_WARM_START_BIT                                     55
#define SEAT_WARM_BIT_LEN                                       1
#define SEAT_AIR_START_BIT                                      54
#define SEAT_AIR_BIT_LEN                                        1
/* AIR_CTRL */
#define AIR_CTRL_ID                                             0x0003
#define AIR_CTRL_LEN                                            2
#define AIR_VALID_START_BIT                                     63
#define AIR_VALID_BIT_LEN                                       1
#define AIR_MODE_START_BIT                                      52
#define AIR_MODE_BIT_LEN                                        4
/* AIR_TEM */
#define AIR_TEM_ID                                              0x0004
#define AIR_TEM_LEN                                             1
#define AIR_TEM_START_BIT                                       56
#define AIR_TEM_BIT_LEN                                         8
/* VEH_TRACK_CTRL */
#define VEH_TRACK_CTRL_ID                                       0x0005
#define VEH_TRACK_CTRL_LEN                                      2
#define REMOTE_VEH_TRACK_VALID_START_BIT                        63
#define REMOTE_VEH_TRACK_VALID_BIT_LEN                          1
#define REMOTE_VEH_TRACK_START_BIT                              55
#define REMOTE_VEH_TRACK_BIT_LEN                                1
/* ENGINE_CTRL */
#define ENGINE_CTRL_ID                                          0x0006
#define ENGINE_CTRL_LEN                                         2
#define REMOTE_ENGINE_SS_VALID_START_BIT                        63
#define REMOTE_ENGINE_SS_VALID_BIT_LEN                          1
#define REMOTE_ENGINE_SS_START_BIT                              55
#define REMOTE_ENGINE_SS_BIT_LEN                                1
/* CHARGE_CTRL */
#define CHARGE_CTRL_ID                                          0x0007
#define CHARGE_CTRL_LEN                                         2
#define REMOTE_CHARGE_VALID_START_BIT                           63
#define REMOTE_CHARGE_VALID_BIT_LEN                             1
#define REMOTE_CHARGE_START_BIT                                 55
#define REMOTE_CHARGE_BIT_LEN                                   1
/* EKEY_CTRL */
#define EKEY_CTRL_ID                                            0x0008
#define EKEY_CTRL_LEN                                           2
#define REMOTE_ED_VALID_START_BIT                               63
#define REMOTE_ED_VALID_BIT_LEN                                 1
#define REMOTE_ED_START_BIT                                     55
#define REMOTE_ED_BIT_LEN                                       1
/* MOTOR_CTRL */
#define MOTOR_CTRL_ID                                           0x0009
#define MOTOR_CTRL_LEN                                          2
#define REMOTE_POWER_VALID_START_BIT                            63
#define REMOTE_POWER_VALID_BIT_LEN                              1
#define REMOTE_POWER_START_BIT                                  55
#define REMOTE_POWER_BIT_LEN                                    1
/* PRI_INFO_CTRL */
#define PRI_INFO_CTRL_ID                                        0x000A
#define PRI_INFO_CTRL_LEN                                       2
#define REMOTE_PRI_INFO_LOCK_VALID_START_BIT                    63
#define REMOTE_PRI_INFO_LOCK_VALID_BIT_LEN                      1
#define REMOTE_PRI_INFO_LOCK_START_BIT                          55
#define REMOTE_PRI_INFO_LOCK_BIT_LEN                            1
/* SUN_ROOF_CTRL */
#define SUN_ROOF_CTRL_ID                                        0x000B
#define SUN_ROOF_CTRL_LEN                                       2
#define REMOTE_SUN_ROOF_VALID_START_BIT                         63
#define REMOTE_SUN_ROOF_VALID_BIT_LEN                           1
#define REMOTE_SUN_ROOF_START_BIT                               55
#define REMOTE_SUN_ROOF_BIT_LEN                                 1
/* UPDATE_NOTIFY */
#define UPDATE_NOTIFY_ID                                        0x000C
/* TRANSFER_DATA */
#define TRANSFER_DATA_ID                                        0x000D
/* REQ_SW_NO */
#define REQ_SW_NO_ID                                            0x000E
/* HEARTBEAT */
#define HEARTBEAT_ID                                            0x000F
/* UPDATE_ECU_NOTIFY */
#define UPDATE_ECU_NOTIFY_ID                                    0x0010
#define UPDATE_ECU_NOTIFY_LEN                                   5
#define ECU_TYPE0_START_BIT                                     56
#define ECU_TYPE0_BIT_LEN                                       8
#define ECU_FW_SIZE_START_BIT                                   24
#define ECU_FW_SIZE_BIT_LEN                                     32
/* TRANSFER_ECU_DATA */
#define TRANSFER_ECU_DATA_ID                                    0x0011
#define TRANSFER_ECU_DATA_LEN                                   3
#define ECU_TYPE1_START_BIT                                     56
#define ECU_TYPE1_BIT_LEN                                       8
#define ECU_BLOCK_NUM_START_BIT                                 40
#define ECU_BLOCK_NUM_BIT_LEN                                   16
/* REQ_ECU_SW_NO */
#define REQ_ECU_SW_NO_ID                                        0x0012
#define REQ_ECU_SW_NO_LEN                                       1
#define ECU_TYPE2_START_BIT                                     56
#define ECU_TYPE2_BIT_LEN                                       8
/* CP_AIR_CTRL */
#define CP_AIR_CTRL_ID                                          0x0013
#define CP_AIR_CTRL_LEN                                         1
#define AIR_ON_START_BIT                                        63
#define AIR_ON_BIT_LEN                                          1
#define AIR_FRONT_DEFROST_START_BIT                             62
#define AIR_FRONT_DEFROST_BIT_LEN                               1
#define AIR_REAR_DEFROST_START_BIT                              61
#define AIR_REAR_DEFROST_BIT_LEN                                1
#define AIR_MAX_START_BIT                                       60
#define AIR_MAX_BIT_LEN                                         1
#define AIR_AUTO_START_BIT                                      59
#define AIR_AUTO_BIT_LEN                                        1
#define AIR_RECIRCULATION_START_BIT                             58
#define AIR_RECIRCULATION_BIT_LEN                               1
#define AIR_IONIZER_START_BIT                                   57
#define AIR_IONIZER_BIT_LEN                                     1
#define AIR_OFF_BUTTON_START_BIT                                56
#define AIR_OFF_BUTTON_BIT_LEN                                  1
/* CP_AIR_CTRL_DRIVER_TEMP */
#define CP_AIR_CTRL_DRIVER_TEMP_ID                              0x0014
#define CP_AIR_CTRL_DRIVER_TEMP_LEN                             1
#define AIR_DRIVER_TEMP_START_BIT                               56
#define AIR_DRIVER_TEMP_BIT_LEN                                 8
/* CP_AIR_CTRL_PASS_TEMP */
#define CP_AIR_CTRL_PASS_TEMP_ID                                0x0015
#define CP_AIR_CTRL_PASS_TEMP_LEN                               1
#define AIR_PASSENGER_TEMP_START_BIT                            56
#define AIR_PASSENGER_TEMP_BIT_LEN                              8
/* CP_AIR_CTRL_FLAP_POS */
#define CP_AIR_CTRL_FLAP_POS_ID                                 0x0016
#define CP_AIR_CTRL_FLAP_POS_LEN                                1
#define AIR_FLAP_POSITION_START_BIT                             60
#define AIR_FLAP_POSITION_BIT_LEN                               4
/* CP_AIR_CTRL_BLOW_LEVEL */
#define CP_AIR_CTRL_BLOW_LEVEL_ID                               0x0017
#define CP_AIR_CTRL_BLOW_LEVEL_LEN                              1
#define AIR_BLOW_LEVEL_START_BIT                                60
#define AIR_BLOW_LEVEL_BIT_LEN                                  4

#endif /* __GEN_DOWNSTREAM_H__ */
