/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : extWdog.h
**     Project     : lowersystem
**     Processor   : S32K144_64
**     Component   : ewm
**     Version     : Component SDK_S32K1xx_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-03-06, 11:16, # CodeGen: 374
**     Contents    :
**         EWM_DRV_Init                   - status_t EWM_DRV_Init(uint32_t instance,const ewm_init_config_t * config);
**         EWM_DRV_GetDefaultConfig       - void EWM_DRV_GetDefaultConfig(ewm_init_config_t * config);
**         EWM_DRV_Refresh                - void EWM_DRV_Refresh(uint32_t instance);
**         EWM_DRV_GetInputPinAssertLogic - ewm_in_assert_logic_t EWM_DRV_GetInputPinAssertLogic(uint32_t instance);
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file extWdog.h
** @version 01.00
*/         
/*!
**  @addtogroup extWdog_module extWdog module documentation
**  @{
*/         
#ifndef extWdog_H
#define extWdog_H
/* MODULE extWdog. */
/* Include inherited beans */
#include "clockMan1.h"
#include "Cpu.h"
#include "ewm_driver.h"

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, global macro not referenced
 * There are global macros defined to be used by the integrator and another one used as include guard.
 */
 
/*! @brief Device instance number */
#define EXTWDOG 0UL


/*! @brief Declarations of configuration structures */
extern ewm_init_config_t extWdog_Config0;

#endif
/* ifndef extWdog_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
